
import javax.swing.JOptionPane;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tejas
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        this.setSize(700,500);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PageTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FnameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DOBField = new javax.swing.JTextField();
        BackBut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        UIDField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PwField = new javax.swing.JTextField();
        SignUpBut = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        PNField = new javax.swing.JTextField();
        TCbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PageTitle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        PageTitle.setText("XYZ Bank Account Creation");
        getContentPane().add(PageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 20));

        jLabel1.setText("Please Enter The Requested Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setText("Full Name         : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        FnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(FnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 430, -1));

        jLabel3.setText("Date Of Birth  : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        DOBField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBFieldActionPerformed(evt);
            }
        });
        getContentPane().add(DOBField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 430, -1));

        BackBut.setText("Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });
        getContentPane().add(BackBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel6.setText("User ID         : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));
        getContentPane().add(UIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 210, -1));

        jLabel7.setText("Password   :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));
        getContentPane().add(PwField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 210, -1));

        SignUpBut.setText("Sign Up");
        SignUpBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jLabel8.setText("Ph. Number      :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        getContentPane().add(PNField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 430, -1));

        TCbox.setText("I Agree To The Terms And Conditions");
        getContentPane().add(TCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameFieldActionPerformed

    private void DOBFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBFieldActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
                    this.setVisible(false);
                    LoginPage lp = new LoginPage();
                    lp.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BackButActionPerformed

    private void SignUpButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButActionPerformed
        Random r = new Random();
        int a = r.nextInt(92929929);
        if(TCbox.isSelected())
        {JOptionPane.showMessageDialog(this,"Account Created. Your Acc No. is: "+String.valueOf(a));}
        else
        {
            JOptionPane.showMessageDialog(this, "Please Agree To T&C");
        }
    }//GEN-LAST:event_SignUpButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and dfeel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JTextField DOBField;
    private javax.swing.JTextField FnameField;
    private javax.swing.JTextField PNField;
    private javax.swing.JLabel PageTitle;
    private javax.swing.JTextField PwField;
    private javax.swing.JButton SignUpBut;
    private javax.swing.JCheckBox TCbox;
    private javax.swing.JTextField UIDField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
