/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class CustomerPortal extends javax.swing.JFrame {

    /**
     * Creates new form CustomerPortal
     */
    public CustomerPortal() {
        this.setSize(400,300);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TransactBut = new javax.swing.JButton();
        LoanBut = new javax.swing.JButton();
        IssueBut = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        MyProfile = new javax.swing.JMenu();
        DetailsMenuItem = new javax.swing.JMenuItem();
        LogOutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/person.png"))); // NOI18N
        getContentPane().add(jLabel1);

        TransactBut.setForeground(new java.awt.Color(36, 49, 249));
        TransactBut.setText("Transact");
        TransactBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactButActionPerformed(evt);
            }
        });
        getContentPane().add(TransactBut);

        LoanBut.setText("Apply For Loan");
        LoanBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanButActionPerformed(evt);
            }
        });
        getContentPane().add(LoanBut);

        IssueBut.setText("Raise Issue");
        IssueBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueButActionPerformed(evt);
            }
        });
        getContentPane().add(IssueBut);

        MyProfile.setText("My Profile");

        DetailsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        DetailsMenuItem.setText("Details");
        DetailsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsMenuItemActionPerformed(evt);
            }
        });
        MyProfile.add(DetailsMenuItem);

        LogOutMenu.setText("Log Out");
        LogOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuActionPerformed(evt);
            }
        });
        MyProfile.add(LogOutMenu);

        jMenuBar2.add(MyProfile);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DetailsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsMenuItemActionPerformed
                    DetailsPage dp = new DetailsPage();
                    this.setVisible(false);
                    dp.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_DetailsMenuItemActionPerformed

    private void LogOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuActionPerformed
                      this.setVisible(false);
                      LoginPage lp = new LoginPage();
                      lp.setVisible(true);
    }//GEN-LAST:event_LogOutMenuActionPerformed

    private void TransactButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactButActionPerformed
                                    TransactPage tp = new TransactPage();
                                    this.setVisible(false);
                                    tp.setVisible(true);
    }//GEN-LAST:event_TransactButActionPerformed

    private void IssueButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueButActionPerformed
                                    IssuePage ip = new IssuePage();
                                    this.setVisible(false);
                                    ip.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_IssueButActionPerformed

    private void LoanButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanButActionPerformed
                                     LoanApply la = new LoanApply();
                                     this.setVisible(false);
                                     la.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_LoanButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DetailsMenuItem;
    private javax.swing.JButton IssueBut;
    private javax.swing.JButton LoanBut;
    private javax.swing.JMenuItem LogOutMenu;
    private javax.swing.JMenu MyProfile;
    private javax.swing.JButton TransactBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
